version: "3"
services:
  web:
    build:
      context: .
    ports:
      - "8080:80"
    networks:
      - backend
    depends_on:
      - redis_db
    env_file:
      - web-variables.env
  redis_db:
    image: redis:3.2.8
    ports:
      - "6379:6379"
    container_name: redis_db
    networks:
      - backend
networks:
  backend:
